=== MathieuAvila/milendall/generator/schema/generator.level.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://incoherent.com/schemas/level.json",

    "properties": {
        "name": { "$ref": "#/definitions/name" },
        "$schema": {
            "type": "string",
            "description": "Link to this schema"
        },
        "game_type": {
            "type" : "object",
            "description": "Allowed game types",
            "properties": {
                "single_mode" : {
                    "type": "object",
                    "description": "For single player mode",
                    "properties": {
                        "execution_time" : {
                            "type": "number",
                            "description": "Allowed execution time"
                        },
                        "entry_point_room" :  {
                            "type": "string",
                            "description": "Room where player is spawned"
                        },
                        "end_point_room" :  {
                            "type": "string",
                            "description": "Room where player has won"
                        },
                        "entry_point_position" :  {
                            "type": "array",
                            "description": "Position where player is spawned",
                            "items": {
                                "type": "number",
                                "maxItems": 3,
                                "minItems": 3
                            }
                        }
                    },
                    "required": [
                        "execution_time",
                        "entry_point_room",
                        "end_point_room"
                    ],
                    "additionalProperties": false
                }
            }
        },

        "section": {
            "type": "string",
            "description": "Section ID to which it belongs"
        },

        "gates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "gate_id": {
                        "type": "string",
                        "description": "ID of the gate"
                    },
                    "structure_class": {
                        "type": "string",
                        "description": "The general class name of the structure. Example 'rectangular'"
                    },
                    "dressing_class": {
                        "type": "string",
                        "description": "The general class name of the dressing. Example 'raw'"
                    },
                    "structure_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "structure_private" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_private" :  { "type": "object", "description": "private parameters at instantiation. Content depends on class" },
                    "connect" :  {
                        "type": "array",
                        "description": "List of rooms that are connected by this gates. Must be two !",
                        "minimum": 2,
                        "maximum": 2
                    },
                    "accessible":  {
                        "type": "string",
                        "description": "Declares if objects can pass through initially. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "visible":  {
                        "type": "string",
                        "description": "Declares if it is visually detectable. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "see_through":  {
                        "type": "string",
                        "description": "Declares if is possible to see through it. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "scale" : {
                        "type": "number",
                        "description": "Change of scale when going forward; Reverse in the opposite direction."
                    },
                    "events" : {
                        "type": "array",
                        "description": "List of events that this gate reacts upon, and associated actions",
                        "items": {
                            "type": "object",
                            "properties" : {
                                "action": {
                                    "type": "string",
                                    "description": "On action amongst: open (can go through), close (cannot go through), visible (can see through), invisible (cannot see through), accessible, inaccessible"
                                },
                                "direction" : {
                                    "type": "string",
                                    "description": "Which direction is changed. Defaults to both."
                                },
                                "on_trigger" : {
                                    "type": "string",
                                    "description": "The trigger name that makes this action happen"
                                },
                                "on_property" : {
                                    "type": "string",
                                    "description": "Which characteristic is changed: visible, accessible, see_thourgh"
                                },
                                "to_value" : {
                                    "type": "string",
                                    "description": "To which value it is changed. Can be true,false,switch"
                                }
                            },
                            "required": [
                                "action", "on_trigger", "on_property", "to_value"
                            ],
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "gate_id",
                    "connect"
                ]
            }
        },
        "rooms": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "room_id": {
                        "type": "string",
                        "description": "Section name to which it belongs"
                    },
                    "name": { "$ref": "#/definitions/name" },
                    "structure_class": {
                        "type": "string",
                        "description": "The general class name of the structure. Example 'rectangular'"
                    },
                    "dressing_class": {
                        "type": "string",
                        "description": "The general class name of the dressing. Example 'raw'"
                    },
                    "structure_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "structure_private" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_private" :  { "type": "object", "description": "private parameters at instantiation. Content depends on class" },

                    "triggers" : {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "description": "Trigger definition",
                            "properties": {
                                "trigger_id" : {
                                    "type": "string",
                                    "description": "Unique ID"
                                },
                                "type" : {
                                    "type": "string",
                                    "description": "trigger type. If undefined, room is free to choose what best suits it.",
                                    "enum": ["walk-on", "hidden-walk-on", "button"]
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "trigger_id",
                                "type"
                            ]
                        }
                     }
                 },
                "additionalProperties": false,
                "required": [
                    "room_id",
                    "name"
                ]
            }
        }
    },
    "required": [
        "name",
        "game_type",
        "section",
        "rooms",
        "gates"
    ],
    "additionalProperties": false,

    "definitions": {
        "name": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "A name in one language",
                "properties": {
                    "lang" : {
                        "type": "string",
                        "description": "The language. Must be unique."
                    },
                    "value" : {
                        "type": "string",
                        "description": "Name in that language"
                    }
                }
            },
            "description": "A name in multiple languages. Defaults to 'en'"
        }
    }
}

=== MathieuAvila/milendall/generator/samples/room_tubular2_default/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room2",
            "entry_point_position": [ 2.0, 1.0, 2.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "room2",
            "name" : [ { "lang": "en", "value" : "room2"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "tube2",
            "name" : [ { "lang": "en", "value" : "tube"}  ],
            "structure_class" : "tubular2",
            "structure_parameters": {
            },
            "dressing_class" : "basic"
        }
    ],
    "gates" : [
        {
            "gate_id" : "r1_tube",
            "connect" : [ "room1", "tube2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "r2_tube",
            "connect" : [ "tube2", "room2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
     ]
}

=== MathieuAvila/milendall/generator/samples/sphere_and_rectangular/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room1",
            "entry_point_position": [ 12.0, 1.0, 0.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "sphere",
            "dressing_class" : "sphere",
            "structure_parameters": {
                "setup": {
                 "radius": 10,
                 "lats": 50,
                 "longs": 50
                }
            }
        },
        {
            "room_id" : "room2",
            "name" : [ { "lang": "en", "value" : "room2"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        }
    ],
    "gates" : [
        {
            "gate_id" : "r1r2",
            "connect" : [ "room1", "room2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
     ]
}

=== MathieuAvila/milendall/generator/samples/sphere/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room1",
            "entry_point_position": [ 22.0, 1.0, 0.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "sphere",
            "dressing_class" : "basic",
            "structure_parameters": {
                "setup": {
                 "radius": 20,
                 "longs": 60
                }
               }
        }
    ],
    "gates" : [
    ]
}

=== MathieuAvila/milendall/generator/pygenerator/test/test_samples/level/2_room_1_gate/level-user-instantiated.json
{
 "$schema": "../../../../schema/generator.level.schema.json",
 "name": [
  {
   "lang": "en",
   "value": "Simple Level"
  }
 ],
 "section": "samples",
 "game_type": {
  "single_mode": {
   "execution_time": 10.0,
   "entry_point_room": "room1",
   "end_point_room": "room3"
  }
 },
 "rooms": [
  {
   "room_id": "room1",
   "name": [
    {
     "lang": "en",
     "value": "nightmare"
    }
   ],
   "structure_class": "brick_structure_1",
   "dressing_class": "room_dressing_1",
   "triggers": [
    {
     "trigger_id": "open1",
     "type": "button"
    }
   ],
   "structure_private": {
    "size": [
     10.0,
     10.0,
     2.5
    ]
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "room_id": "room2",
   "name": [
    {
     "lang": "en",
     "value": "heaven"
    }
   ],
   "triggers": [
    {
     "trigger_id": "open2",
     "type": "walk-on"
    }
   ],
   "structure_class": "brick_structure_1",
   "structure_private": {
    "size": [
     10.0,
     10.0,
     2.5
    ]
   },
   "structure_parameters": {},
   "dressing_class": "room_dressing_1",
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "room_id": "room3",
   "name": [
    {
     "lang": "en",
     "value": "earth"
    }
   ],
   "triggers": [
    {
     "trigger_id": "close3",
     "type": "walk-on"
    }
   ],
   "structure_class": "brick_structure_1",
   "structure_private": {
    "size": [
     10.0,
     10.0,
     2.5
    ]
   },
   "structure_parameters": {},
   "dressing_class": "room_dressing_1",
   "dressing_private": {},
   "dressing_parameters": {}
  }
 ],
 "gates": [
  {
   "gate_id": "r3r2",
   "connect": [
    "room3",
    "room2"
   ],
   "accessible": "from-to",
   "structure_class": "gate_structure_1",
   "structure_private": {
    "private1": true
   },
   "structure_parameters": {},
   "dressing_class": "gate_dressing_1",
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "gate_id": "r1r2",
   "connect": [
    "room1",
    "room2"
   ],
   "accessible": "from-to",
   "visible": "from-to",
   "see_through": "from-to",
   "structure_class": "gate_structure_1",
   "dressing_class": "gate_dressing_1",
   "structure_private": {
    "private1": true
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "gate_id": "r1r3",
   "connect": [
    "room1",
    "room3"
   ],
   "structure_class": "gate_structure_1",
   "structure_private": {
    "private1": true
   },
   "structure_parameters": {},
   "dressing_class": "gate_dressing_1",
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "gate_id": "r1r1",
   "connect": [
    "room1",
    "room1"
   ],
   "scale": 0.5,
   "events": [
    {
     "action": "open",
     "direction": "from-to",
     "on_trigger": "open1",
     "on_property": "accessible",
     "to_value": "true"
    },
    {
     "action": "visible",
     "direction": "from-to",
     "on_trigger": "open2",
     "on_property": "accessible",
     "to_value": "false"
    },
    {
     "action": "close",
     "on_trigger": "close3",
     "on_property": "accessible",
     "to_value": "false"
    },
    {
     "action": "invisible",
     "on_trigger": "close3",
     "on_property": "accessible",
     "to_value": "false"
    }
   ],
   "structure_class": "gate_structure_1",
   "structure_private": {
    "private1": true
   },
   "structure_parameters": {},
   "dressing_class": "gate_dressing_1",
   "dressing_private": {},
   "dressing_parameters": {}
  }
 ]
}

=== MathieuAvila/milendall/game/test/sample/3_rooms_3_gates/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level with 2 rooms and 1 gate"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room2"
        }
    },

    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "hell"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "room2",
            "structure_class" : "rectangular",
            "dressing_class" : "basic",
            "name" : [ { "lang": "en", "value" : "heaven"} ]
        },
        {
            "room_id" : "room3",
            "structure_class" : "rectangular",
            "dressing_class" : "basic",
            "name" : [ { "lang": "en", "value" : "earth"} ]
        }
    ],
    "gates" : [
        {
            "gate_id" : "r1r2",
            "connect" : [ "room1", "room2"],
            "accessible" : "from-to",
            "visible" : "from-to",
            "see_through" : "from-to",

            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "r2r1",
            "connect" : [ "room2", "room1"],
            "accessible" : "from-to",
            "visible" : "from-to",
            "see_through" : "from-to",

            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "r3r1",
            "connect" : [ "room3", "room1"],
            "accessible" : "from-to",
            "visible" : "from-to",
            "see_through" : "from-to",

            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
    ]
}

=== MathieuAvila/milendall/generator/samples/tubular/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room2",
            "entry_point_position": [ 2.0, 1.0, 2.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "room2",
            "name" : [ { "lang": "en", "value" : "room2"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "tube",
            "name" : [ { "lang": "en", "value" : "tube"}  ],
            "structure_class" : "tubular",
            "structure_parameters": {
                "setup": {
                    "segments_nr": 5,
                    "increment": 1.0,
                    "f_step" : "[ [-0.1, i/5.0 ], [1.7, i/5.0 ], [1.7, 1.6+i/5.0 ], [-0.1, 1.6+i/5.0 ] ]",
                    "script_up" : ["1.0", "0.0"],
                    "script_gravity" : ["-1.0", "0.0"]
                }
            },
            "dressing_class" : "basic"
        }
    ],
    "gates" : [
        {
            "gate_id" : "r1_tube",
            "connect" : [ "room1", "tube"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "r2_tube",
            "connect" : [ "tube", "room2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
     ]
}

=== MathieuAvila/milendall/generator/samples/room_tubular2_parameterized/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room2",
            "entry_point_position": [ 2.0, 1.0, 2.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "room2",
            "name" : [ { "lang": "en", "value" : "room2"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "tube2",
            "name" : [ { "lang": "en", "value" : "tube"}  ],
            "structure_class" : "tubular2",
            "structure_parameters": {
                "segments_nr": 11,
                "func": [
                    "c = math.cos(t*6.28/10.0)",
                    "s = math.sin(t*6.28/10.0)",
                    "values = [",
                    "[0.0 + t/1.0, c*5.0,      s*5.0],",
                    "[1.6 + t/1.0, c*5.0,      s*5.0],",
                    "[1.6 + t/1.0, c*6.8,      s*6.8],",
                    "[0.0 + t/1.0, c*6.8,      s*6.8],",
                    "]"
                ],
                "mode_up_gravity" : "follow",
                "gravity_factor" : 0.1
            },
            "dressing_class" : "basic"
        }
    ],
    "gates" : [
        {
            "gate_id" : "r1_tube",
            "connect" : [ "room1", "tube2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "r2_tube",
            "connect" : [ "tube2", "room2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
     ]
}

=== MathieuAvila/milendall/game/test/sample/3_rooms_3_gates/level-instance.json
{
 "$schema": "../../schema/generator.level.schema.json",
 "name": [
  {
   "lang": "en",
   "value": "Simple Level with 3 rooms and 3 gates"
  }
 ],
 "section": "samples",
 "game_type": {
  "single_mode": {
   "execution_time": 10.0,
   "entry_point_room": "room1",
   "end_point_room": "room2"
  }
 },
 "rooms": [
  {
   "room_id": "room1",
   "name": [
    {
     "lang": "en",
     "value": "hell"
    }
   ],
   "structure_class": "rectangular",
   "dressing_class": "basic",
   "structure_private": {
    "gate_pre_post_range": [
     [
      1.0,
      1.0
     ],
     [
      4.0,
      4.0
     ]
    ],
    "height_over_gate_range": [
     1.0,
     1.0
    ],
    "height_over_gate": 1.0,
    "wall_pre_post_range": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "wall_pre_post": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "setup": [
     [
      {
       "gate": "r1r2",
       "pre": 1.0,
       "post": 4.0
      },
      {
        "gate": "r2r1",
        "pre": 1.0,
        "post": 4.0
       }
     ],
     [{
        "gate": "r3r1",
        "pre": 1.0,
        "post": 4.0
       }],
     [
     ],
     [
     ],
     []
    ]
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "room_id": "room2",
   "structure_class": "rectangular",
   "dressing_class": "basic",
   "name": [
    {
     "lang": "en",
     "value": "heaven"
    }
   ],
   "structure_private": {
    "gate_pre_post_range": [
     [
      1.0,
      1.0
     ],
     [
      4.0,
      4.0
     ]
    ],
    "height_over_gate_range": [
     1.0,
     1.0
    ],
    "height_over_gate": 1.0,
    "wall_pre_post_range": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "wall_pre_post": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "setup": [
     [{
        "gate": "r1r2",
        "pre": 1.0,
        "post": 4.0
       },{
        "gate": "r2r1",
        "pre": 1.0,
        "post": 4.0
       }],
     [],
     [],
     [],
     []
    ]
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "room_id": "room3",
   "structure_class": "rectangular",
   "dressing_class": "basic",
   "name": [
    {
     "lang": "en",
     "value": "earth"
    }
   ],
   "structure_private": {
    "gate_pre_post_range": [
     [
      1.0,
      1.0
     ],
     [
      4.0,
      4.0
     ]
    ],
    "height_over_gate_range": [
     1.0,
     1.0
    ],
    "height_over_gate": 1.0,
    "wall_pre_post_range": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "wall_pre_post": [
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ],
     [
      2.0,
      2.0
     ]
    ],
    "setup": [
     [],
     [
      {
       "gate": "r3r1",
       "pre": 1.0,
       "post": 4.0
      }
     ],
     [],
     [],
     []
    ]
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  }
 ],
 "gates": [
  {
   "gate_id": "r1r2",
   "connect": [
    "room1",
    "room2"
   ],
   "accessible": "from-to",
   "visible": "from-to",
   "see_through": "from-to",
   "structure_class": "simple_door",
   "dressing_class": "basic",
   "structure_private": {
    "geometry": {
     "portal": [
      2.5,
      2.5
     ],
     "margin": [
      1.0,
      1.0
     ],
     "floor": [
      "x0"
     ]
    },
    "shift": {
     "x_floor_start_ext": -0.5,
     "x_floor_start_int": 0.1,
     "x_floor_end_int": 2.4,
     "x_floor_end_ext": 3.0,
     "x_up_start_ext": -0.3,
     "x_up_start_int": 0.2,
     "x_up_end_int": 2.3,
     "x_up_end_ext": 2.8,
     "y_up_start_ext": 2.7,
     "y_up_start_int": 2.5,
     "y_up_end_ext": 2.7,
     "y_up_end_int": 2.5,
     "w_in": 1.2,
     "w_out": -0.2
    }
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "gate_id": "r2r1",
   "connect": [
    "room2",
    "room1"
   ],
   "accessible": "from-to",
   "visible": "from-to",
   "see_through": "from-to",
   "structure_class": "simple_door",
   "dressing_class": "basic",
   "structure_private": {
    "geometry": {
     "portal": [
      2.5,
      2.5
     ],
     "margin": [
      1.0,
      1.0
     ],
     "floor": [
      "x0"
     ]
    },
    "shift": {
     "x_floor_start_ext": -0.5,
     "x_floor_start_int": 0.1,
     "x_floor_end_int": 2.4,
     "x_floor_end_ext": 3.0,
     "x_up_start_ext": -0.3,
     "x_up_start_int": 0.2,
     "x_up_end_int": 2.3,
     "x_up_end_ext": 2.8,
     "y_up_start_ext": 2.7,
     "y_up_start_int": 2.5,
     "y_up_end_ext": 2.7,
     "y_up_end_int": 2.5,
     "w_in": 1.2,
     "w_out": -0.2
    }
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  },
  {
   "gate_id": "r3r1",
   "connect": [
    "room3",
    "room1"
   ],
   "accessible": "from-to",
   "visible": "from-to",
   "see_through": "from-to",
   "structure_class": "simple_door",
   "dressing_class": "basic",
   "structure_private": {
    "geometry": {
     "portal": [
      2.5,
      2.5
     ],
     "margin": [
      1.0,
      1.0
     ],
     "floor": [
      "x0"
     ]
    },
    "shift": {
     "x_floor_start_ext": -0.5,
     "x_floor_start_int": 0.1,
     "x_floor_end_int": 2.4,
     "x_floor_end_ext": 3.0,
     "x_up_start_ext": -0.3,
     "x_up_start_int": 0.2,
     "x_up_end_int": 2.3,
     "x_up_end_ext": 2.8,
     "y_up_start_ext": 2.7,
     "y_up_start_int": 2.5,
     "y_up_end_ext": 2.7,
     "y_up_end_int": 2.5,
     "w_in": 1.2,
     "w_out": -0.2
    }
   },
   "structure_parameters": {},
   "dressing_private": {},
   "dressing_parameters": {}
  }
 ]
}
