=== MathieuAvila/milendall/generator/schema/generator.level.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://incoherent.com/schemas/level.json",

    "properties": {
        "name": { "$ref": "#/definitions/name" },
        "$schema": {
            "type": "string",
            "description": "Link to this schema"
        },
        "game_type": {
            "type" : "object",
            "description": "Allowed game types",
            "properties": {
                "single_mode" : {
                    "type": "object",
                    "description": "For single player mode",
                    "properties": {
                        "execution_time" : {
                            "type": "number",
                            "description": "Allowed execution time"
                        },
                        "entry_point_room" :  {
                            "type": "string",
                            "description": "Room where player is spawned"
                        },
                        "end_point_room" :  {
                            "type": "string",
                            "description": "Room where player has won"
                        },
                        "entry_point_position" :  {
                            "type": "array",
                            "description": "Position where player is spawned",
                            "items": {
                                "type": "number",
                                "maxItems": 3,
                                "minItems": 3
                            }
                        }
                    },
                    "required": [
                        "execution_time",
                        "entry_point_room",
                        "end_point_room"
                    ],
                    "additionalProperties": false
                }
            }
        },

        "section": {
            "type": "string",
            "description": "Section ID to which it belongs"
        },

        "gates": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "gate_id": {
                        "type": "string",
                        "description": "ID of the gate"
                    },
                    "structure_class": {
                        "type": "string",
                        "description": "The general class name of the structure. Example 'rectangular'"
                    },
                    "dressing_class": {
                        "type": "string",
                        "description": "The general class name of the dressing. Example 'raw'"
                    },
                    "structure_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "structure_private" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_private" :  { "type": "object", "description": "private parameters at instantiation. Content depends on class" },
                    "connect" :  {
                        "type": "array",
                        "description": "List of rooms that are connected by this gates. Must be two !",
                        "minimum": 2,
                        "maximum": 2
                    },
                    "accessible":  {
                        "type": "string",
                        "description": "Declares if objects can pass through initially. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "visible":  {
                        "type": "string",
                        "description": "Declares if it is visually detectable. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "see_through":  {
                        "type": "string",
                        "description": "Declares if is possible to see through it. Defaults to both.",
                        "enum": ["from-to", "to-from", "both"]
                    },
                    "scale" : {
                        "type": "number",
                        "description": "Change of scale when going forward; Reverse in the opposite direction."
                    },
                    "events" : {
                        "type": "array",
                        "description": "List of events that this gate reacts upon, and associated actions",
                        "items": {
                            "type": "object",
                            "properties" : {
                                "action": {
                                    "type": "string",
                                    "description": "On action amongst: open (can go through), close (cannot go through), visible (can see through), invisible (cannot see through), accessible, inaccessible"
                                },
                                "direction" : {
                                    "type": "string",
                                    "description": "Which direction is changed. Defaults to both."
                                },
                                "on_trigger" : {
                                    "type": "string",
                                    "description": "The trigger name that makes this action happen"
                                },
                                "on_property" : {
                                    "type": "string",
                                    "description": "Which characteristic is changed: visible, accessible, see_thourgh"
                                },
                                "to_value" : {
                                    "type": "string",
                                    "description": "To which value it is changed. Can be true,false,switch"
                                }
                            },
                            "required": [
                                "action", "on_trigger", "on_property", "to_value"
                            ],
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "gate_id",
                    "connect"
                ]
            }
        },
        "rooms": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "room_id": {
                        "type": "string",
                        "description": "Section name to which it belongs"
                    },
                    "name": { "$ref": "#/definitions/name" },
                    "structure_class": {
                        "type": "string",
                        "description": "The general class name of the structure. Example 'rectangular'"
                    },
                    "dressing_class": {
                        "type": "string",
                        "description": "The general class name of the dressing. Example 'raw'"
                    },
                    "structure_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "structure_private" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_parameters" : { "type": "object", "description": "general parameters at instantiation. Content depends on class" },
                    "dressing_private" :  { "type": "object", "description": "private parameters at instantiation. Content depends on class" },

                    "triggers" : {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "description": "Trigger definition",
                            "properties": {
                                "trigger_id" : {
                                    "type": "string",
                                    "description": "Unique ID"
                                },
                                "type" : {
                                    "type": "string",
                                    "description": "trigger type. If undefined, room is free to choose what best suits it.",
                                    "enum": ["walk-on", "hidden-walk-on", "button"]
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "trigger_id",
                                "type"
                            ]
                        }
                     }
                 },
                "additionalProperties": false,
                "required": [
                    "room_id",
                    "name"
                ]
            }
        }
    },
    "required": [
        "name",
        "game_type",
        "section",
        "rooms",
        "gates"
    ],
    "additionalProperties": false,

    "definitions": {
        "name": {
            "type": "array",
            "items": {
                "type": "object",
                "description": "A name in one language",
                "properties": {
                    "lang" : {
                        "type": "string",
                        "description": "The language. Must be unique."
                    },
                    "value" : {
                        "type": "string",
                        "description": "Name in that language"
                    }
                }
            },
            "description": "A name in multiple languages. Defaults to 'en'"
        }
    }
}

=== MathieuAvila/milendall/generator/samples/door_with_auto_open/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "room1",
            "end_point_room" : "room2",
            "entry_point_position": [ 2.0, 1.0, 2.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "room1",
            "name" : [ { "lang": "en", "value" : "room1"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        },
        {
            "room_id" : "room2",
            "name" : [ { "lang": "en", "value" : "room2"}  ],
            "structure_class" : "rectangular",
            "dressing_class" : "basic"
        }
    ],
    "gates" : [
        {
            "gate_id" : "door",
            "connect" : [ "room1", "room2"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic",
            "structure_parameters": {
                "door": {
                    "timing" : 0.9,
                    "auto_open" : true,
                    "default_open": true
                }
            }

        }
     ]
}

=== MathieuAvila/milendall/generator/samples/3_spheres/level-user.json
{
    "$schema": "../../schema/generator.level.schema.json",

    "name" : [  { "lang": "en", "value" : "Simple Level"} ],
    "section": "samples",

    "game_type" : {
        "single_mode" : {
            "execution_time" : 10.0,
            "entry_point_room" : "earth",
            "end_point_room" : "earth",
            "entry_point_position": [ 12.0, 1.0, 0.0 ]
        }
    },
    "rooms" : [
        {
            "room_id" : "earth",
            "name" : [ { "lang": "en", "value" : "earth"}  ],
            "structure_class" : "sphere",
            "dressing_class" : "sphere",
            "structure_parameters": {
                "setup": {
                 "radius": 10,
                 "lats": 50,
                 "longs": 50
                }
            },
            "dressing_parameters": {
                "setup": [
                 [
                  "ground",
                  "/common/planets/earth.jpg"
                 ],
                 [
                  "wall",
                  "/common/planets/earth.jpg"
                 ],
                 [
                  "ceiling",
                  "/common/planets/earth.jpg"
                 ]
                ]
               }
        },
        {
            "room_id" : "sun",
            "name" : [ { "lang": "en", "value" : "sun"}  ],
            "structure_class" : "sphere",
            "dressing_class" : "sphere",
            "dressing_parameters": {
                "setup": [
                 [
                  "ground",
                  "/common/planets/sun.jpg"
                 ],
                 [
                  "wall",
                  "/common/planets/sun.jpg"
                 ],
                 [
                  "ceiling",
                  "/common/planets/sun.jpg"
                 ]
                ]
               },
            "structure_parameters": {
                "setup": {
                 "radius": 50,
                 "lats": 50,
                 "longs": 50
                }
            }
        },
        {
            "room_id" : "mars",
            "name" : [ { "lang": "en", "value" : "mars"}  ],
            "structure_class" : "sphere",
            "dressing_class" : "sphere",
            "dressing_parameters": {
                "setup": [
                 [
                  "ground",
                  "/common/planets/mars.jpg"
                 ],
                 [
                  "wall",
                  "/common/planets/mars.jpg"
                 ],
                 [
                  "ceiling",
                  "/common/planets/mars.jpg"
                 ]
                ]
               },
            "structure_parameters": {
                "setup": {
                 "radius": 8,
                 "lats": 50,
                 "longs": 50
                }
            }
        }
    ],
    "gates" : [
        {
            "gate_id" : "earth_sun",
            "connect" : [ "earth", "sun"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        },
        {
            "gate_id" : "earth_mars",
            "connect" : [ "earth", "mars"],
            "accessible" : "from-to",
            "structure_class" : "simple_door",
            "dressing_class" : "basic"
        }
     ]
}
